<?php


namespace Tests;


use KissDev\ChileanRut\Person;
use PHPUnit\Framework\TestCase as BaseTestCase;

/**
 * Class ChileanRutTest
 * @package Tests
 */
class ChileanRutTest extends BaseTestCase
{
    /**
     * @var \KissDev\ChileanRut\Person
     */
    protected $person;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->person = new Person();
        $this->person->rut = '5.126.663-3';
    }

    /**
     * @test
     */
    public function can_cleaned_rut()
    {
        $this->assertEquals('5126663-3', $this->person->clean($this->person->rut));
    }

    /**
     * @test
     */
    public function can_cleaned_rut_without_dash_in_check_digit()
    {
        $this->assertEquals('51266633', $this->person->clean($this->person->rut, false));
    }

    /**
     * @test
     */
    public function has_a_valid_length()
    {
        $this->assertTrue($this->person->hasValidLength($this->person->rut));
    }

    /**
     * @test
     */
    public function has_not_a_valid_length()
    {
        $this->person->rut = '12';
        $this->assertFalse($this->person->hasValidLength($this->person->rut));
    }

    /**
     * @test
     */
    public function get_verify_rut()
    {
        $this->assertTrue($this->person->verify($this->person->rut));
    }

    /**
     * @test
     */
    public function get_not_verify_rut()
    {
        $this->person->rut = '5.126.663-4';
        $this->assertFalse($this->person->verify($this->person->rut));
    }
}